export const italianTranslations: Record<string, string> = {
  "and": "e",
  "or": "o",
  "every": "ogni",
  "day": "giorno",
  "week": "settimana",
  "month": "mese",
  "year": "anno",
  "on": "il",
  "until": "fino al",
  "for": "per",
  "at": "alle",
  "times": "volte",
  "Monday": "lunedì",
  "Tuesday": "martedì",
  "Wednesday": "mercoledì",
  "Thursday": "giovedì",
  "Friday": "venerdì",
  "Saturday": "sabato",
  "Sunday": "domenica",
  "January": "gennaio",
  "February": "febbraio",
  "March": "marzo",
  "April": "aprile",
  "May": "maggio",
  "June": "giugno",
  "July": "luglio",
  "August": "agosto",
  "September": "settembre",
  "October": "ottobre",
  "November": "novembre",
  "December": "dicembre",
};
